all:
	gfortran -c INTERPRETER.F95 FILEM.F95 INPUTM.F95 WAREHOUSE.F95 GENERATEM.F95 SOLVERM.F95 OUTPUTM.F95 GAUSSM.f95 OPERATIONM.F95
	gfortran -g DISCOVERY.F95 INTERPRETER.o FILEM.o INPUTM.o WAREHOUSE.o GAUSSM.o OPERATIONM.o GENERATEM.o SOLVERM.o OUTPUTM.o -o FEM_MFS.out
clean:
	rm -f FEM_MFS.out 
		
