all:
	gfortran -c INTERPRETER.F95 FILEM.F95 INPUTM.F95 WAREHOUSE.F95 GENERATEM.F95 SOLVERM.F95 OUTPUTM.F95 ODEM.F95 GAUSSM.f95
	gfortran -g DISCOVERY.F95 INTERPRETER.o FILEM.o INPUTM.o WAREHOUSE.o GENERATEM.o SOLVERM.o OUTPUTM.o ODEM.o GAUSSM.o -o Test.out
clean:
	rm -f Test.out 
		